apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    name: user-api
    component: service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    name: user-api
    component: api
